#Config.yml
---

- name: Configure limits.conf
  template: 
    src=limits.conf.j2 
    dest=/etc/security/limits.conf 
    owner=root 
    group=root 
    mode=0644

- name: Delete 90-nproc.conf
  shell: rm -rf /etc/security/limits.d/90-nproc.conf

- name: Configure name_is_not_significant.conf
  template: 
    src=90-nproc.conf.j2 
    dest=/etc/security/limits.d/name_is_not_significant.conf 
    owner=root 
    group=root 
    mode=0644

- name: Update sysctl
  sysctl: name={{item.name}} value={{item.value}} ignoreerrors=yes
  with_items:  "{{limits_sysctl}}"

- name: Sysctl -p
  shell: sysctl -p
