# Configure limits.conf
---

- name: Modify limits.conf
  lineinfile: dest=/etc/security/limits.conf insertbefore="^# End of file\S"  line="* - nofile 63536"

- name: Modify 90-nproc.conf
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf regexp=^1024 line="63536"
