#Config.yml
---

- name: Configure limits.conf
  template: 
    src=limits.conf.j2 
    dest=/etc/security/limits.conf 
    owner=root 
    group=root 
    mode=0644

- name: Configure 90-nproc.conf
  template: 
    src=90-nproc.conf.j2 
    dest=/etc/security/limits.d/90-nproc.conf 
    owner=root 
    group=root 
    mode=0644

- name: Update sysctl
  sysctl: name={{item.name}} value={{item.value}} ignoreerrors=yes
  with_items: "{{limits_sysctl}}"

- name: Create /etc/bashrc_cmd_logging
  file: 
    path: /etc/bashrc_cmd_logging
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Configure /etc/bashrc_cmd_logging
  blockinfile:
    dest: /etc/bashrc_cmd_logging
    block: |
      "export PROMPT_COMMAND='RETRN_VAL=$?;logger -p {{ sky_users_syslog_facility }}.debug "cmd-audit: $(whoami) [$$]: $(history 1 | sed "s/^[ ]*[0-9]\+[ ]*//" ) [$RETRN_VAL]"'"

- name: Configure /etc/bashrc
  blockinfile:
    dest: /etc/bashrc
    block: |
      . /etc/bashrc_cmd_logging

- name: Source /etc/bashrc
  shell: source /etc/bashrc
