#Config.yml
---

- name: Ulimit -n
  shell: ulimit -n 63536

- name: Ulimit -u
  shell: ulimit -u 63536

- name: Edit /etc/profile
  lineinfile: dest=/etc/profile line=ulimit -u 63536

- name: Source /etc/profile
  shell: source /etc/profile

- name: Configure limits.conf
  template: src=limits.conf.j2 dest=/etc/security/limits.conf owner=root group=root mode=0644

- name: Configure 90-nproc.conf
  template: src=90-nproc.conf.j2 dest=/etc/security/limits.d/90-nproc.conf owner=root group=root mode=0644

- name: Update sysctl
  sysctl: name={{item.name}} value={{item.value}} ignoreerrors=yes
  with_items:  "{{limits_sysctl}}"

- name: Sysctl -p
  shell: sysctl -p
